### Spring properties
# Service registers under this name
spring:
  application:
    name: ecomm-user-service
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 8090
  #context-path: /catalog

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false

