server:
  port: 8085
  
spring:
  application:
    name: ecomm-product-service
  # web url: http://localhost:8087/h2-console
  # db url: jdbc:h2:file:~/test 
  datasource:
    url: jdbc:h2:file:~/product 
  h2:
    console:
      enabled: true      
    
     
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    
    